version: '3.0'
services:
  socialwiresbackend:
    build: .
    volumes:
      - ./.:/app/
    container_name: socialwiresbackend_server
    restart: always
    ports:
      - 3000:3000
    depends_on: 
      - psgql
  psgql:
    image: postgres:15.1-alpine
    environment:
        POSTGRES_DB: socialwiresbackend_db
        POSTGRES_USER: emanuel
        POSTGRES_PASSWORD: emanuel
    container_name: socialwiresbackend_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
